ORDER_STATUS_CREATED = 'created'
ORDER_STATUS_DELIVERED = 'delivered'
ORDER_STATUS_PROCESSED = 'processed'
ORDER_STATUS_CANCELLED = 'cancelled'

ORDER_STATUSES = [
    (ORDER_STATUS_CREATED, 'создан'),
    (ORDER_STATUS_DELIVERED, 'доставлен'),
    (ORDER_STATUS_PROCESSED, 'обработан'),
    (ORDER_STATUS_CANCELLED, 'отменено')
    ]
