# Generated by Django 3.1.7 on 2021-06-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210309_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, verbose_name='логин')),
                ('password', models.CharField(max_length=128, verbose_name='пароль')),
                ('uuid_token', models.CharField(max_length=150, verbose_name='токен')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ел. адрес')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='отчество')),
                ('phone_number', models.CharField(blank=True, max_length=100, verbose_name='номер телефона')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='адрес')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='номер телефона'),
        ),
    ]
