# Generated by Django 3.1.7 on 2021-06-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210614_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preuser',
            name='uuid_token',
            field=models.CharField(blank=True, max_length=150, verbose_name='токен'),
        ),
    ]
