version: '3.1'

services:
    web:
      image: python:3.8
      ports:
        - 8000:8000
      volumes:
        - ~/online_store:/web_django
      networks:
        - local-apps

networks:
  local-apps:
    driver: bridge
