# Generated by Django 3.1.7 on 2021-03-15 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210309_2259'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0002_auto_20210310_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'корзина', 'verbose_name_plural': 'корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartproduct',
            options={},
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(help_text='товар', through='carts.CartProduct', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(help_text='пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(help_text='корзина', on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='carts.cart'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(help_text='товар в корзине', on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='products.product'),
        ),
    ]
