# Generated by Django 3.1.7 on 2021-03-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.JSONField(blank=True, default=dict, verbose_name='Продукты заказа'),
        ),
    ]
