# Generated by Django 3.1.7 on 2021-06-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210403_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'создан'), ('delivered', 'доставлен'), ('paid', 'оплачен'), ('cancelled', 'отменено')], default='created', max_length=100, verbose_name='статус заказа'),
        ),
    ]
